add solution for 05-lection3/01-tooltip
js-tasks-ru/htmlcss-20210409_zhenya-guziy pull request #10
Opened 2021-05-10 15:07 UTC by zheka1994

2021-05-10 15:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-13 12:28 UTC, GSemikozov requested changes

2021-05-13 12:28 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    hyphens: auto;
кстати, прикольно видеть что кто-то из группы копается чуть глубже в css3-свойствах =)

2021-05-13 12:28 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    visibility: hidden;
если используем visibility вместо display: none, то - элемент не вырывается из потока документа, не смотря на absolute, поэтому он все еще будет занимать место где-то на странице. Поэтому, важно еще скрыть его через opacity: 0 и кроме того дать возможность всем событиям "проваливаться" через него - pointer-events: none

2021-05-26 22:56 UTC, GSemikozov approved these changes

2021-05-26 22:56 UTC, merged