add solution for 03-lection1/main-page
js-tasks-ru/htmlcss-20210409_zhenya-guziy pull request #3
Opened 2021-04-17 15:00 UTC by zheka1994

Добавление главной страницы

2021-04-17 15:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-18 16:07 UTC, GSemikozov requested changes

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +:root {
css-переменные стоит вынести в наш главный css файл - main.css.

Вообще, переменные кроме `--black` слишком специфичны и на таком глобальном уровне их нет смысла использовать. Например, `--footer-content-color` и `--title-color` невозможно переисспользовать, они относятся только к конкретному футеру и конкретному тайтлу; гораздо лучше использовать более универсальную переменную, скажем, `--text-primary` - тогда такую переменную можно использовать для указания цвета основного текста как в футере, так и в других местах. 
`--background-primary-color` - тоже вряд ли можно будет переиспользовать (а смысл css-переменных именно в этом), в случае с нашей страницей этот цвет используется лишь для общего фона страницы, поэтому как вариант можно просто так: `body { background-color:  #F9FAFC; }`

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +.page {
стили для блока page следует вынести в отдельный блок - в` assets/components/page`

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +.header {
то же самое для header - ` assets/components/header`

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +.content {
для content - ` assets/components/content`

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +.footer {
и для footer - ` assets/components/footer`

2021-04-18 16:07 UTC, GSemikozov commented on components/page/page.css
> +    min-height: 100vh;
скорее всего в указании минимальной высоты через 100vh здесь нет смысла, поскольку тогда content будет высотой на 100%, и еще + header и footer, что в итоге добавит вертикальную прокрутку страницы, при том что у нас в главной секции нет никакого контента, а футер пользователь увидит лишь если проскролит вниз.

2021-04-19 21:18 UTC, zheka1994 commented on components/page/page.css
> +:root {
Спасибо за ревью. Вроде поправил все замечания.

2021-04-24 11:04 UTC, GSemikozov requested changes

2021-04-24 11:04 UTC, GSemikozov commented on components/content/content.css
> +    margin-top: -30px;
здесь точно нужен отрицательный марджин? обычно его использует только в крайнем случае, когда это действительно оправданно.

2021-04-24 11:04 UTC, GSemikozov commented on components/nav/nav.css
> +    line-height: 24px;
думаю, еще надо убрать дефолтное нижнее декорирование у ссылки  `text-decoration: none` если это не сделано в общих сбросах стилей.

2021-04-24 11:04 UTC, GSemikozov commented on components/page/page.css
> +@import '../footer/footer.css';
просто в качестве рекомендации: если этот блок .page будет переиспользоваться и для другой страницы, то если мы хотим импортировать стили блоков в какой-то общий файл - лучше это делать в main.css. Если же хотим добавлять лишь те файлы которые соответствуют конкретным подключаемым блокам на конкретной странице - лучше делать это в конкретном html файле в тэге head, тогда на страницу не будут залетать стили которые на ней не используются :)

2021-04-27 08:50 UTC, GSemikozov submitted a review, later dismissed

2021-04-27 08:50 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-04-28 07:39 UTC, GSemikozov approved these changes

2021-04-28 07:39 UTC, merged